### ISSUE TITLE
Init vue project with defined standards

### ISSUE THREAD

**Issue by DinkoMiletic** [chmjs/vue-cli-plugin-nsoft#1]
- [ ] Init vue project
- [ ] Add default dependencies
  - axios
  - lodash
    - force usage of lodash (lodash lint)
  - moment/date-fns (research needed)
  - vuex, router (optional)
- [ ] Project structure (#2)
- [ ] Testing (#3, #8) 
- [ ] Style-guides (#7)
  - eslint airbnb
  - prettier
  - precommit check
- [ ] NPM and ENV config (#6)
 

Additional:
 - different dependency stack (admin, vizulazacija...)
 - html5 mode on

**Comment by aldinezi** [comment]
Maybe we could discuss replacing `moment` library during our team building event, and also showcase the examples of replacing such library with some modular solutions as `date-fns`.

**Comment by DinkoMiletic** [comment]
Do you think that we need lodash? Most of lodash functionality is available using vanilla JavaScript (ES6).

See [lodash vs native](https://codeburst.io/why-you-shouldnt-use-lodash-anymore-and-use-pure-javascript-instead-c397df51a66)

**Comment by pandzicivan** [comment]
Maybe to make this optional through configuration steps? Lodash is modular, so developer can import whatever he needs. Sure, native is faster, but there are still some functions which aren't supported natively - debounce and throttle for example

**Comment by pandzicivan** [comment]
Also what do you think of adding fetch to packages?

**Comment by aldinezi** [comment]
In my opinion, I prefer usage of `lodash` in our projects, because the way it handles passed arguments. As seen on majority of our sentry events, we have troubles accessing object properties, in which case most of lodash methods behave much more nicely, no matter what you pass to it. On the other hand, most of native methods require non undefined variables to be called upon, and we need to write checks. Lodash's methods do it internally. That said, I vote for lodash.

**Comment by DinkoMiletic** [comment]
Fine. Let's init vue with lodash and axios. Later we can move those deps to configuration.

**Comment by DinkoMiletic** [comment]
This is done in #9
