### ISSUE TITLE
Research testing part

### ISSUE THREAD

**Issue by DinkoMiletic** [chmjs/vue-cli-plugin-nsoft#3]
- Testing and test files location
- E2E Testing and test files location
- Code coverage and code quality

 - jtest
 - jtest code coverage
 - location of file per component
- e2e? nightwatch, cypress, pupeeter

**Comment by manico** [comment]
Since we had a lot of practice with unit testing and vue my recommendation would be:

- vue test utils
- jest
- test files should be located next to file (xy.js and xy.spec.js) as this will force us to cretae js files for specific purpose
- automatic code coverage (codecov)
- automatic code quality (codebeat)

**Comment by DinkoMiletic** [comment]
Did you use end to end testing tools?

**Comment by manico** [comment]
Not that much in Chameleon project.
I belive Nightwatch is recommended.

**Comment by DinkoMiletic** [comment]
To conclude:
 - vue test utils
 - jest
 - test files should be located next to file
 - automatic code coverage (codecov) & automatic code quality (codebeat)
 - Nightwatch as end to end tool
